kind: Service
apiVersion: v1
metadata:
  name: {{ template "nfs-storage.fullname" . }}
  labels:
    app: {{ template "nfs-storage.fullname" . }}
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
    - name: rpcbind-udp
      port: 111
      protocol: UDP
  selector:
    app: {{ template "nfs-storage.fullname" . }}
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "nfs-storage.fullname" . }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "nfs-storage.fullname" . }}
    spec:
      serviceAccount: {{ template "nfs-storage.fullname" . }}-nfs-provisioner
      containers:
        - name: {{ template "nfs-storage.fullname" . }}
          image: "{{ .Values.image }}:{{ .Values.imageVersion }}"
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner={{ .Values.nfsserver }}"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: nfs-provisioner
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          volumeMounts:
            - name: export-volume
              mountPath: /export
      volumes:
        - name: export-volume
          hostPath:
            path: /srv