apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "nfs-storage.fullname" . }}
  labels:
    app: {{ template "nfs-storage.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ template "nfs-storage.fullname" . }}