{{- if .Values.rbacEnable }}
apiVersion: v1
kind: List
items:
- apiVersion: {{template "rbacApiVersion" . }}
  kind: ClusterRole
  metadata:
    name: nfs:cluster
  rules:
    - apiGroups: [""]
      resources: ["persistentvolumes"]
      verbs: ["get", "list", "watch", "create", "delete"]
    - apiGroups: [""]
      resources: ["persistentvolumeclaims"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["storage.k8s.io"]
      resources: ["storageclasses"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["list", "watch", "create", "update", "patch"]
    - apiGroups: [""]
      resources: ["services", "endpoints"]
      verbs: ["get"]
    - apiGroups: ["extensions"]
      resources: ["podsecuritypolicies"]
      resourceNames: ["nfs-provisioner"]
      verbs: ["use"]
- apiVersion: {{template "rbacApiVersion" . }}
  kind: ClusterRoleBinding
  metadata:
    name: external-nfs
  subjects:
    - kind: ServiceAccount
      name: "{{ .Values.serviceAccount }}"
      namespace: "{{ .Release.Namespace }}"
  roleRef:
    kind: ClusterRole
    name: nfs:cluster
    apiGroup: rbac.authorization.k8s.io
- apiVersion: {{template "rbacApiVersion" . }}
  kind: ClusterRoleBinding
  metadata:
    name: {{ template "nfs-storage.fullname" . }}-radmin
  subjects:
    - kind: ServiceAccount
      name: "{{ .Values.serviceAccount }}"
      namespace: "{{ .Release.Namespace }}"
  roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io
{{end}}